// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoC0K7qGLi2g3drg4LuML6jf2KZRpqR2U',
    appId: '1:372955814414:web:01a508b52420814d6f3a5f',
    messagingSenderId: '372955814414',
    projectId: 'login-56f35',
    authDomain: 'login-56f35.firebaseapp.com',
    storageBucket: 'login-56f35.appspot.com',
    measurementId: 'G-SZFMCWZFK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmI1QIKBbm_8g8qrZ-RKd_egZ5qxcB6Kc',
    appId: '1:372955814414:android:a2343833330959f76f3a5f',
    messagingSenderId: '372955814414',
    projectId: 'login-56f35',
    storageBucket: 'login-56f35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjDyAI6mmtY8mi3MxEztb7JmGk4SslTs',
    appId: '1:372955814414:ios:8a9ef932cf34f3126f3a5f',
    messagingSenderId: '372955814414',
    projectId: 'login-56f35',
    storageBucket: 'login-56f35.appspot.com',
    androidClientId: '372955814414-4pbl3upijo4eff6kkh0fq43vhqr8krpc.apps.googleusercontent.com',
    iosClientId: '372955814414-lsd7rkk5h0tjo28msfafapns4i9on1sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationLogins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYjDyAI6mmtY8mi3MxEztb7JmGk4SslTs',
    appId: '1:372955814414:ios:a2845be02ec922b26f3a5f',
    messagingSenderId: '372955814414',
    projectId: 'login-56f35',
    storageBucket: 'login-56f35.appspot.com',
    androidClientId: '372955814414-4pbl3upijo4eff6kkh0fq43vhqr8krpc.apps.googleusercontent.com',
    iosClientId: '372955814414-iq2angvlbce0t3sokf62en3m8oafnnv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationLogins.RunnerTests',
  );
}
